import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/Navbar/Navbar'
import useScrollPosition from '@/hooks/useScrollPosition'
import { useEffect } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const scrollPosition = useScrollPosition();
  return (
    <>
      <Head>
        <title>Aliquo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <header className={styles.header}>
          {
            scrollPosition > 41 && (
              <Navbar />
            )
          }
        </header>
        <section className={styles.firstView}>
          <h1>
            <a href="#main">
              The Decentralized Reserve Asset Protocol
            </a>
          </h1>
        </section>
        <section className={styles.mainContent} id="main">
          
        </section>
      </main>
    </>
  )
}
