import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.scss'
import Navbar from '@/components/Navbar/Navbar'
import useScrollPosition from '@/hooks/useScrollPosition'

export default function Home() {
  const scrollPosition = useScrollPosition();
  return (
    <>
      <Head>
        <title>Aliquo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <header className={styles.header}>
          {
            scrollPosition > 41 && (
              <Navbar />
            )
          }
        </header>
        <section className={styles.firstView}>
          <h1>
            <a href="#main">
              The Decentralized Reserve Asset Protocol
            <div className={styles.downArrow} />
            </a>
          </h1>
        </section>
        <section className={styles.mainContent} id="main">
          {/* 3 sections: 1 - 3 cards in a row; 2 - AQ1 SVG sample 3 - Footer */}
        </section>
      </main>
    </>
  )
}
